spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${spring.datasource.host}:5432/test-db
    username: test
    password: test@123
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwttoken.secret: mysecretkey
# in milliseconds (5 mins)
jwttoken.expiration: 300000
